name: div-free
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy>=2.0
  - fenics-dolfinx=0.8.0
  - mpich
  - scipy
  - pandas
  - matplotlib
  - pyvista
  - cuda-cudart
  - cuda-version=12
  - pip
  - pip:
    - jax[cuda12]==0.9.0
    - jaxlib==0.9.0
    - jaxopt